### ISSUE TITLE
COMMUNICATION_ERROR is the binding expired?

### ISSUE THREAD

**Issue by AlessandroLacroce** [mvalla/openhab-addons#105]
Hi, 
since a couple of hours I keep getting the following error:

`[ERROR] [org.openwebnet.AbstractOpenGateway ] - ERROR IN Java $MODULE$: connection cannot be established`

followed by:
`openwebnet:bus_gateway:mybridge' changed from UNKNOWN to OFFLINE (COMMUNICATION_ERROR)`

Am I the only one? Is the binding expired?

Thanks!

**Comment by modenet** [comment]
same problem

**Comment by Vincentpigree** [comment]
no problem for me yet

**Comment by modenet** [comment]
> no problem for me yet

try to reboot...

**Comment by jebu** [comment]
Same here, openwebnet-lib-0.9.21 has a date check set to expire on 2020-03-14 15:00:00

**Comment by gilbertococchi** [comment]
+1 happening here as well.
I don't believe @mvalla is working on this anymore.

Anyone can point to what can be done to extend the Binding to change the expiration?

**Comment by tottarello** [comment]
Anyone can point to what can be done to extend the Binding to change the expiration? ????

**Comment by gilbertococchi** [comment]
Hi @tottarello, I believe we can try rebuilding the library https://github.com/openwebnet/rx-openwebnet and adding the new version to the org.openhab.binding.openwebnet/ binding here: https://github.com/mvalla/openhab2-addons/tree/openwebnet/bundles/org.openhab.binding.openwebnet/lib

**Comment by tottarello** [comment]
I don't have the skills if you can change it would help me

**Comment by vaaduz** [comment]
Hi to all,
I have the same issue, it would be nice find someone who can help us.
Tnx

**Comment by Vincentpigree** [comment]
See here can be the solution
https://community.openhab.org/t/bticino-openwebnet-new-openhab2-binding-ready-for-testing/43377/1049

**Comment by vaaduz** [comment]
Thx Vincentpigree, I solved

**Comment by mvalla** [comment]
fixed in version 2.5.0.M4

**Comment by nefero** [comment]
Hi Guys, I have the issue again, it's possible to have an M5 version?
Thank you
Ciao
Stefano

**Comment by vaaduz** [comment]
Hi to all, from yesterday I have problem with my gateway, with this error:
[org.openwebnet.AbstractOpenGateway ] - ERROR IN Java $MODULE$: connection cannot be established

Probabily the version 2.5.0.M4 is expired

**Comment by mvalla** [comment]
fixed in version 2.5.0

**Comment by FrancescoRisso** [comment]
Hi all.
I had the same problem yesterday, so I decided to uninstall and reinstall the openwebnet binding to be sure to have the latest version.
I was trying to install it manually because from the paper UI it didn't work (I tried to reinstall it that way, but the problem was not solved. Also for the first install, the binding only worked when I installed it manually).
The doubt I had while doing this is that I found very similar versions of the binding: one on this [mvalla repository](https://github.com/mvalla/openhab-addons/tree/openwebnet-dev/bundles/org.openhab.binding.openwebnet), and one on the [openhab repository](https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.openwebnet). They look similar, but they are not identical. Which one is the correct/best one?

Thanks for your help

Ciao,
           Francesco
